# Generated by Django 6.0.1 on 2026-01-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_status_options_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(help_text='Enter the status name (e.g., Published, Draft, Archived).', max_length=128, unique=True),
        ),
    ]
